[build-system]
requires = ["setuptools", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "pylibcue"
version = "0.1.0"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["pylibcue"]
