name: CI/CD

on:
  push:
    branches: ['main']
    tags: ['v*']
  workflow_dispatch:

jobs:
  build-linux:
    name: Build and Test (Linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Install dependencies
      run: python -m pip install --upgrade setuptools Cython build abi3audit auditwheel
    - name: Run tests
      run: make test
    - name: Build sdist
      run: make sdist
    - name: Upload sdist
      uses: actions/upload-artifact@v7
      with:
        name: sdist
        path: dist/pylibcue*.tar.gz
    - name: Build wheel
      run: make wheel
    - name: Auditwheel
      run: auditwheel repair dist/*.whl && abi3audit wheelhouse/*.whl --verbose
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheel_linux
        path: wheelhouse/*.whl
        if-no-files-found: error

  build:
    name: Build and Test
    needs: build-linux
    strategy:
      matrix:
        os: ['windows', 'macos']
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: Download sdist
      uses: actions/download-artifact@v8
      with:
        name: sdist
    - name: Extract sdist
      shell: bash
      run: tar xzf pylibcue*.tar.gz --strip-components=1
    - uses: actions/setup-python@v7
      with:
        python-version: 3.14
    - name: Install dependencies
      run: python -m pip install --upgrade setuptools Cython build abi3audit
    - name: Run tests
      run: make test
    - name: Build wheel
      run: make wheel
    - name: Auditwheel
      run: abi3audit dist/*.whl --verbose
    - name: Upload wheels
      uses: actions/upload-artifact@v7
      with:
        name: wheel_${{ matrix.os }}
        path: dist/*.whl
        if-no-files-found: error

  release:
    name: Create Release
    needs: [build-linux, build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Download wheels
      uses: actions/download-artifact@v8
      with:
        path: dist/
        merge-multiple: true
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ github.ref_name }}
        draft: true
        artifacts: "dist/*.whl,dist/*.tar.gz"
